In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
train_dataset = pd.read_csv('train.csv')
test_dataset = pd.read_csv('test.csv')
id = test_dataset['Id']
test_ids = id.values

In [4]:
selected_columns = ['GrLivArea', 'BedroomAbvGr', 'FullBath', 'SalePrice']
train_dataset = train_dataset[selected_columns]
print(train_dataset.head())

   GrLivArea  BedroomAbvGr  FullBath  SalePrice
0       1710             3         2     208500
1       1262             3         2     181500
2       1786             3         2     223500
3       1717             3         1     140000
4       2198             4         2     250000


In [5]:
x_train = train_dataset.iloc[:, :-1].values
y_train = train_dataset.iloc[:, -1].values
print(x_train)
print(y_train)

[[1710    3    2]
 [1262    3    2]
 [1786    3    2]
 ...
 [2340    4    2]
 [1078    2    1]
 [1256    3    1]]
[208500 181500 223500 ... 266500 142125 147500]


In [6]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [7]:
y_pred_train = regressor.predict(x_train)
print(y_pred_train)

[211526.41442352 162218.76100172 219891.10562901 ... 253005.96982441
 140132.04717924 131863.70225277]


In [8]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=regressor, X=x_train, y=y_train, cv=10)
print(accuracies.mean())
print(accuracies.std())

0.5782822878463451
0.07989064400115926


In [9]:
selected_columns_test = ['GrLivArea', 'BedroomAbvGr', 'FullBath']
test_datasets = test_dataset[selected_columns_test]
print(test_datasets.head())

   GrLivArea  BedroomAbvGr  FullBath
0        896             2         1
1       1329             3         1
2       1629             3         2
3       1604             3         2
4       1280             2         2


In [10]:
x_test = test_datasets.iloc[:, :].values
print(x_test)

[[ 896    2    1]
 [1329    3    1]
 [1629    3    2]
 ...
 [1224    4    1]
 [ 970    3    1]
 [2000    3    2]]


In [11]:
y_pred_test = regressor.predict(x_test)
print(y_pred_test)

[120100.81297664 139898.20827909 202611.4145861  ... 100482.39478483
 100386.04850582 243444.31507603]


In [12]:
predictions = pd.DataFrame({'Id': test_ids, 'SalePrice': y_pred_test})
print(predictions)

        Id      SalePrice
0     1461  120100.812977
1     1462  139898.208279
2     1463  202611.414586
3     1464  199859.871426
4     1465  192059.204300
...    ...            ...
1454  2915  113813.579125
1455  2916  113813.579125
1456  2917  100482.394785
1457  2918  100386.048506
1458  2919  243444.315076

[1459 rows x 2 columns]


In [13]:
from sklearn.metrics import r2_score
print(r2_score(y_train, y_pred_train))

0.5832212987566321


In [14]:
predictions.to_csv('Prediction.csv', index=False)